--q1
BEGIN 
FOR i IN 1..6 LOOP
DBMS_OUTPUT.PUT_LINE(i * 2);
END LOOP;
END;
/

--q2
BEGIN
FOR i IN REVERSE 10..20 LOOP
DBMS_OUTPUT.PUT_LINE(i);
END LOOP;
END;
/

--Q3
DECLARE 
num NUMBER := &num;  --& USED FOR USER INPUT
BEGIN
IF MOD(num , 2) = 0 THEN
DBMS_OUTPUT.PUT_LINE('EVEN');
ELSE
DBMS_OUTPUT.PUT_LINE('ODD');
END IF;
END;
/

--Q4
DECLARE 
num NUMBER := &num;  --& USED FOR USER INPUT
i NUMBER := 1;

BEGIN 
WHILE i <= 12 LOOP
DBMS_OUTPUT.PUT_LINE(num || 'x' || i || '=' || num * i);
i := i + 1;
END LOOP;
END;
/


--q5
DECLARE
V_NAME EMPLOYEES.FIRST_NAME%TYPE;

BEGIN 
SELECT
FIRST_NAME INTO V_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
DBMS_OUTPUT.PUT_LINE('The first name of the employee with ID = 100 is ' || V_NAME);
END;
/

--Q6
CREATE OR REPLACE PROCEDURE get_email(P_EMPID IN EMPLOYEES.EMPLOYEE_ID%TYPE) AS
V_EMAIL EMPLOYEES.EMAIL%TYPE;
BEGIN 
SELECT
EMAIL INTO V_EMAIL FROM EMPLOYEES WHERE EMPLOYEE_ID = P_EMPID;
DBMS_OUTPUT.PUT_LINE('EmpID ' || P_EMPID || ': ' || V_EMAIL);
END;

--TEST FOR Q6
EXEC get_email(103);

--q7
CREATE OR REPLACE PROCEDURE GET_EMP_CITY(P_EMPID IN EMPLOYEES.EMPLOYEE_ID%TYPE) AS
  V_CITY LOCATIONS.CITY%TYPE;
BEGIN
  SELECT L.CITY
  INTO V_CITY
  FROM EMPLOYEES E
  JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
  WHERE E.EMPLOYEE_ID = P_EMPID;

  DBMS_OUTPUT.PUT_LINE('EMPLOYEE ' || P_EMPID || ' WORKS IN ' || V_CITY);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO DATA FOUND FOR EMPLOYEE ID ' || P_EMPID);
END;
/

--Q8
CREATE OR REPLACE PROCEDURE GET_IT_EMPLOYEES AS
  CURSOR C_IT IS
    SELECT E.FIRST_NAME, J.JOB_TITLE
    FROM EMPLOYEES E
    JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN JOBS J ON E.JOB_ID = J.JOB_ID
    WHERE D.DEPARTMENT_NAME = 'IT';
    
  V_NAME EMPLOYEES.FIRST_NAME%TYPE;
  V_JOB  JOBS.JOB_TITLE%TYPE;
BEGIN
  OPEN C_IT;
  LOOP
    FETCH C_IT INTO V_NAME, V_JOB;
    EXIT WHEN C_IT%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(V_NAME || ' - ' || V_JOB);
  END LOOP;
  CLOSE C_IT;
END;
/

--Q9
CREATE OR REPLACE PROCEDURE GET_JOB_HISTORY AS
  CURSOR C_HIST IS
    SELECT E.FIRST_NAME, JH.JOB_ID, JH.START_DATE
    FROM EMPLOYEES E
    JOIN JOB_HISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
    WHERE E.DEPARTMENT_ID = 50;
BEGIN
  FOR REC IN C_HIST LOOP
    DBMS_OUTPUT.PUT_LINE(REC.FIRST_NAME || ' - ' || REC.JOB_ID || ' - ' || REC.START_DATE);
  END LOOP;
END;
/


--Q10
DECLARE 
SAL1 EMPLOYEES.SALARY%TYPE;
SAL2 EMPLOYEES.SALARY%TYPE;

BEGIN 
SELECT SALARY INTO SAL1 FROM EMPLOYEES WHERE employee_id = 120;
SELECT SALARY INTO SAL1 FROM EMPLOYEES WHERE employee_id = 122;

UPDATE EMPLOYEES SET SALARY = SAL2 WHERE EMPLOYEE_ID = 122;
UPDATE EMPLOYEES SET SALARY = SAL2 WHERE EMPLOYEE_ID = 120;

END;
/

--Q11
DECLARE 
V_HIRE_DATE EMPLOYEES.HIRE_DATE%TYPE;
V_EXP NUMBER;

BEGIN 
SELECT 
HIRE_DATE INTO V_HIRE_DATE FROM EMPLOYEES WHERE EMPLOYEE_ID = 115;
V_EXP := FLOOR(MONTHS_BETWEEN(SYSDATE, V_HIRE_DATE) / 12);

UPDATE EMPLOYEES
SET SALARY = CASE
WHEN V_EXP > 10 THEN SALARY * 1.20;
WHEN V_EXP > 5 THEN SALARY * 1.10;
ELSE SALARY * 1.05;

DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT || ' row(s) updated.');

END;
/

--q12
CREATE OR REPLACE PROCEDURE UPDATE_EMP_COMMISSION AS
V_SALARY EMPLOYEES.SALARY%TYPE;
V_HIRE_DATE EMPLOYEES.HIRE_DATE%TYPE;
V_EXP NUMBER;
V_COMM NUMBER;
BEGIN
SELECT SALARY, HIRE_DATE 
INTO V_SALARY, V_HIRE_DATE
FROM EMPLOYEES 
WHERE EMPLOYEE_ID = 152;

V_EXP := FLOOR(MONTHS_BETWEEN(SYSDATE, V_HIRE_DATE) / 12);

IF V_SALARY > 10000 THEN
V_COMM := 0.40;
ELSIF V_SALARY < 10000 AND V_EXP > 10 THEN
V_COMM := 0.35;
ELSIF V_SALARY < 3000 THEN
V_COMM := 0.25;
ELSE
V_COMM := 0.15;
END IF;

UPDATE EMPLOYEES 
SET COMMISSION_PCT = V_COMM 
WHERE EMPLOYEE_ID = 152;

DBMS_OUTPUT.PUT_LINE('COMMISSION UPDATED TO ' || (V_COMM * 100) || '%');
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID 152 NOT FOUND.');
END;
/

--q13
CREATE OR REPLACE PROCEDURE DELETE_EMPLOYEE(P_EMPID IN EMPLOYEES.EMPLOYEE_ID%TYPE) AS
V_MGR EMPLOYEES.MANAGER_ID%TYPE;
BEGIN
SELECT MANAGER_ID 
INTO V_MGR 
FROM EMPLOYEES 
WHERE EMPLOYEE_ID = P_EMPID;


UPDATE EMPLOYEES 
SET MANAGER_ID = V_MGR 
WHERE MANAGER_ID = P_EMPID;


UPDATE DEPARTMENTS 
SET MANAGER_ID = V_MGR 
WHERE MANAGER_ID = P_EMPID;

  
DELETE FROM EMPLOYEES 
WHERE EMPLOYEE_ID = P_EMPID;

DBMS_OUTPUT.PUT_LINE('EMPLOYEE ' || P_EMPID || ' DELETED SUCCESSFULLY.');
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID ' || P_EMPID || ' NOT FOUND.');
END;
/
