
--Q1
--a)
SELECT
    E.FIRST_NAME,
    E.LAST_NAME,
    E.DEPARTMENT_ID,
    D.DEPARTMENT_NAME
FROM
    Employees E, Departments D
WHERE
    E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--b)
SELECT
    E.FIRST_NAME,
    E.LAST_NAME,
    DEPARTMENT_ID,
    D.DEPARTMENT_NAME
FROM
    Employees E
JOIN DEPARTMENTS D USING (DEPARTMENT_ID);

--C)
SELECT
    E.FIRST_NAME,
    E.LAST_NAME,
    E.DEPARTMENT_ID,
    D.DEPARTMENT_NAME
FROM
    Employees E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--D)
SELECT
    FIRST_NAME,
    LAST_NAME,
    DEPARTMENT_ID,
    DEPARTMENT_NAME
FROM
    Employees
NATURAL JOIN
    Departments;


--E) NO DIFFERENCE
--F) 

--Q2
SELECT
    E.FIRST_NAME,
    E.LAST_NAME,
    D.DEPARTMENT_NAME,
    L.CITY,
    L.STATE_PROVINCE
FROM
    EMPLOYEES E
INNER JOIN
    DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN
    LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;

--Q3
SELECT
E.FIRST_NAME,
E.LAST_NAME,
E.salary,
J.job_title

FROM EMPLOYEES E 
JOIN JOBS J ON (J.JOB_ID = E.JOB_ID);

--Q4
SELECT
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FULLNAME,
    E.DEPARTMENT_ID,
    D.DEPARTMENT_NAME
FROM
    EMPLOYEES E
JOIN
    DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE
    D.DEPARTMENT_NAME IN ('Finance','Accounting');

-- q5

SELECT
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FULLNAME,
    D.DEPARTMENT_NAME,
    E.JOB_ID,
    L.CITY || ', ' || L.STATE_PROVINCE AS "Location"
FROM
    EMPLOYEES E
JOIN
    DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN
    LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;

--q6
SELECT
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FULLNAME,
    D.DEPARTMENT_NAME,
    E.JOB_ID,
    L.CITY || ', ' || L.STATE_PROVINCE AS "Location"
FROM
    EMPLOYEES E
JOIN
    DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN
    LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE
    L.CITY LIKE 'S%';

--q7
SELECT
    E.*,
    M.FIRST_NAME || ' ' || M.LAST_NAME AS Manager_FullName
FROM
    EMPLOYEES E               
LEFT JOIN
    EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID; 

--Q8
SELECT
    D.DEPARTMENT_NAME,
    L.CITY,
    L.STATE_PROVINCE
FROM
    DEPARTMENTS D
JOIN
    LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE
    D.DEPARTMENT_NAME LIKE '%ing';

--Q9
SELECT
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FULLNAME,
    E.DEPARTMENT_ID,
    D.DEPARTMENT_NAME
FROM
    EMPLOYEES E
LEFT JOIN
    DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--Q10
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
LEFT JOIN EMPLOYEES
ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE EMPLOYEES.DEPARTMENT_ID IS NULL;

--Q11
SELECT E.FIRST_NAME AS EMP_FIRST_NAME, E.LAST_NAME AS EMP_LAST_NAME, M.FIRST_NAME AS MAN_FIRST_NAME, M.LAST_NAME AS MAN_LAST_NAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID;

--Q12
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.EMAIL, E.PHONE_NUMBER, E.HIRE_DATE, E.JOB_ID, E.SALARY, E.COMMISSION_PCT, E.MANAGER_ID, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.MANAGER_ID IS NULL;

--Q13
SELECT DEPARTMENTS.DEPARTMENT_NAME, LOCATIONS.STREET_ADDRESS, LOCATIONS.POSTAL_CODE, LOCATIONS.CITY, LOCATIONS.STATE_PROVINCE, COUNTRIES.COUNTRY_NAME, REGIONS.REGION_NAME
FROM (((DEPARTMENTS
INNER JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID)
INNER JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID)
INNER JOIN REGIONS ON COUNTRIES.REGION_ID = REGIONS.REGION_ID)

--Q14
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLOYEE_FULL_NAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE E.SALARY > M.SALARY;

--Q15
SELECT EMPLOYEES.FIRST_NAME || ' ' || EMPLOYEES.LAST_NAME AS EMPLOYEE_NAME, JOBS.JOB_TITLE, DEPARTMENTS.DEPARTMENT_NAME, JOB_HISTORY.START_DATE
FROM (((EMPLOYEES
INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID)
INNER JOIN JOB_HISTORY ON EMPLOYEES.EMPLOYEE_ID = JOB_HISTORY.EMPLOYEE_ID)
INNER JOIN JOBS ON JOB_HISTORY.JOB_ID = JOBS.JOB_ID)
WHERE JOB_HISTORY.START_DATE BETWEEN '01-JAN-93' AND '01-DEC-95';

--Q16
SELECT *
FROM EMPLOYEES E
FULL OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--Q17
SELECT DEPARTMENT_NAME, ROUND(AVG(SALARY), 2) AS AVG_DEPT_SALARY
FROM DEPARTMENTS D
INNER JOIN EMPLOYEES E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

--Q18
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLOYEE_NAME, J.JOB_TITLE, (M.MAX_SALARY - E.SALARY) AS SALARY_DIFFERENCE
FROM EMPLOYEES E
JOIN JOBS J 
ON E.JOB_ID = J.JOB_ID
JOIN (SELECT JOB_ID, MAX(SALARY) AS MAX_SALARY
FROM EMPLOYEES
GROUP BY JOB_ID
) M
ON E.JOB_ID = M.JOB_ID
ORDER BY SALARY_DIFFERENCE ASC;

--Q19
SELECT JOB_TITLE, COUNT(*) AS NUM_OF_EMPLOYEES
FROM EMPLOYEES E
INNER JOIN JOBS J
ON E.JOB_ID = J.JOB_ID
GROUP BY JOB_TITLE;

--Q20
SELECT CITY, COUNT(DISTINCT DEPARTMENT_NAME) AS NUM_OF_DEPTS
FROM DEPARTMENTS D
INNER JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
GROUP BY CITY;
